### ISSUE TITLE
Var Binary is generated uncorrecly

### ISSUE THREAD

**Issue by dfsantamaria** [web3j/web3j-cli#40]
[faucet.sol.txt](https://github.com/web3j/web3j-cli/files/4307440/faucet.sol.txt)
Using web3j solidity command produces an uncorrect variable BINARY in the java wrapper file. For example, it produces

` public static final String BINARY = "{\r\n"
            + "\t\"linkReferences\": {},\r\n"
            + "\t\"object\": \"608060405234801561001057600080fd5b5060e78061001f6000396000f3fe608060405260043610601c5760003560e01c80632e1a7d4d14601e575b005b348015602957600080fd5b50605360048036036020811015603e57600080fd5b81019080803590602001909291905050506055565b005b67016345785d8a0000811115606957600080fd5b3373ffffffffffffffffffffffffffffffffffffffff166108fc829081150290604051600060405180830381858888f1935050505015801560ae573d6000803e3d6000fd5b505056fea265627a7a7231582084c311b9ac0189ec88df157c4bb2f87670475f5c6e5a3e1272778ceddc746d6064736f6c634300050c0032\",\r\n"
            + "\t\"opcodes\": \"PUSH1 0x80 PUSH1 0x40 MSTORE CALLVALUE DUP1 ISZERO PUSH2 0x10 JUMPI PUSH1 0x0 DUP1 REVERT JUMPDEST POP PUSH1 0xE7 DUP1 PUSH2 0x1F PUSH1 0x0 CODECOPY PUSH1 0x0 RETURN INVALID PUSH1 0x80 PUSH1 0x40 MSTORE PUSH1 0x4 CALLDATASIZE LT PUSH1 0x1C JUMPI PUSH1 0x0 CALLDATALOAD PUSH1 0xE0 SHR DUP1 PUSH4 0x2E1A7D4D EQ PUSH1 0x1E JUMPI JUMPDEST STOP JUMPDEST CALLVALUE DUP1 ISZERO PUSH1 0x29 JUMPI PUSH1 0x0 DUP1 REVERT JUMPDEST POP PUSH1 0x53 PUSH1 0x4 DUP1 CALLDATASIZE SUB PUSH1 0x20 DUP2 LT ISZERO PUSH1 0x3E JUMPI PUSH1 0x0 DUP1 REVERT JUMPDEST DUP2 ADD SWAP1 DUP1 DUP1 CALLDATALOAD SWAP1 PUSH1 0x20 ADD SWAP1 SWAP3 SWAP2 SWAP1 POP POP POP PUSH1 0x55 JUMP JUMPDEST STOP JUMPDEST PUSH8 0x16345785D8A0000 DUP2 GT ISZERO PUSH1 0x69 JUMPI PUSH1 0x0 DUP1 REVERT JUMPDEST CALLER PUSH20 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF AND PUSH2 0x8FC DUP3 SWAP1 DUP2 ISZERO MUL SWAP1 PUSH1 0x40 MLOAD PUSH1 0x0 PUSH1 0x40 MLOAD DUP1 DUP4 SUB DUP2 DUP6 DUP9 DUP9 CALL SWAP4 POP POP POP POP ISZERO DUP1 ISZERO PUSH1 0xAE JUMPI RETURNDATASIZE PUSH1 0x0 DUP1 RETURNDATACOPY RETURNDATASIZE PUSH1 0x0 REVERT JUMPDEST POP POP JUMP INVALID LOG2 PUSH6 0x627A7A723158 KECCAK256 DUP5 0xc3 GT 0xb9 0xac ADD DUP10 0xec DUP9 0xdf ISZERO PUSH29 0x4BB2F87670475F5C6E5A3E1272778CEDDC746D6064736F6C634300050C STOP ORIGIN \",\r\n"
            + "\t\"sourceMap\": \"130:445:0:-;;;;8:9:-1;5:2;;;30:1;27;20:12;5:2;130:445:0;;;;;;;\"\r\n"
            + "}";`
From the ABI and BIN attached, generated from Remix-IDE.
[faucet.abi.txt](https://github.com/web3j/web3j-cli/files/4307377/faucet.abi.txt)
[faucet.bin.txt](https://github.com/web3j/web3j-cli/files/4307378/faucet.bin.txt)

**Comment by cfelde** [comment]
Unable to reproduce, could you share a small example project?

**Comment by dfsantamaria** [comment]
I have attached the abi and bin files used in my case.

**Comment by cfelde** [comment]
Your bin file should only contain the binary. Please make sure that's the case. It might be easier if you go with a project using the gradle plugin, like what's produced by using the web3j new example project.
