### ISSUE TITLE
ABIv2 wrapper generation with 4.6.0 

### ISSUE THREAD

**Issue by jeremyjams** [web3j/web3j-cli#49]
Hi Web3j team, many thanks for your latest v4.6.0 web3j release https://github.com/web3j/web3j/releases/tag/v4.6.0!

When do you plan a v4.6.0 web3j-cli release featuring Java wrapper generation from Solidity ABIv2?

**Comment by duprass** [comment]
Any updates?

**Comment by fatimaleal** [comment]
Yap, any news about new web3j-cli releases? The last release of web3j-cli is 4.5.16 and the web3j is already 4.6.1.

**Comment by conor10** [comment]
Hi, we’d encourage you to try using the [Epirus CLI](https://www.web3labs.com/epirus) instead - it provides all of the functionality of the CLI plus more. We’re looking for beta users currently.

All of the Web3j CLI functionality is present there. It also includes additional value add features (a management portal and network connectivity) which will require a subscription longer term. However, we’ll waive these for our early beta users.

**Comment by conor10** [comment]
Source repo is available [here](https://github.com/epirus-io/epirus-cli).

**Comment by jeremyjams** [comment]
Thanks for the reference @conor10 . Is it the end of support for classic web3j-cli?

**Comment by conor10** [comment]
Not the end of support - Epirus CLI preserves all of its functionality - same commands etc. We just wanted to bring the binary in line with our other products under the Epirus name. Epirus just adds a ton of additional features, but other then the name change it shouldn't impact existing users in any way.

Plus its easier to have everything in one place.

Hopefully all our docs and repos are updated now so there won't be further confusion.

**Comment by conor10** [comment]
Just to be clear - you don't need to sign up for any services to use the Epirus CLI if you follow the instructions on the CLI source repo. It's only if you want to have wallet management and node connectivity for deployment that the wider platform comes into play.

**Comment by jeremyjams** [comment]
Thanks for clarifications :+1:
