### ISSUE TITLE
Project generation Failed with Java 8

### ISSUE THREAD

**Issue by gabirezzo** [web3j/web3j-cli#77]
Unable to build and start the project using Java version 8. 

![WhatsApp Image 2021-12-13 at 22 19 29](https://user-images.githubusercontent.com/33133399/145918351-1cd5f6d2-b1ec-4c77-ba41-399159036bff.jpeg)

Details can be found in the log below.

[logs.zip](https://github.com/web3j/web3j-cli/files/7708066/logs.zip)

With Java 11 the problem doesn't happen. 

## Environment
Web3j version: 4.8.7
CLI: 1.4.1
Java version : 8
Operating System : Windows

**Comment by mohamedelshami** [comment]
@gabirezzo this appears to caused by missing class during classloading.

`java.lang.NullPointerException
	at org.web3j.codegen.unit.gen.CompilerClassLoader.compileClass(CompilerClassLoader.java:86)`

I suspect this is due to using Java 8, other than OpenJDK which is the only Java 8 being currently maintained.
