### ISSUE TITLE
release of web3j-cli corresponding to web3j 4.9.0?

### ISSUE THREAD

**Issue by monperrus** [web3j/web3j-cli#81]
The default binary from https://get.web3j.io is web3j-1.4.1 which depends on web3j 4.8.4.

The latest version of web3j is [v4.9.0](https://github.com/web3j/web3j/releases/tag/v4.9.0).

Where can we download a version of web3j-cli which embeds web3j 4.9.0?

Thanks!

**Comment by mohamedelshami** [comment]
@monperrus latest release of webj3-cli v1.4.2 now updated to use web3j-4.9.4
