### ISSUE TITLE
Update master to use latest Web3j 4.9.1 version

### ISSUE THREAD

**Issue by SweeXordious** [web3j/web3j-cli#84]
As discussed under https://github.com/web3j/web3j/issues/1361, The project needs to update dependency of web3j and bump it to `4.9.1`.

**Comment by drinkcoffee** [comment]
It would be great if this could be resolved.

**Comment by drinkcoffee** [comment]
@SweeXordious  do you know when this is likely to be released?

**Comment by SweeXordious** [comment]
@mohamedelshami Any idea please ?

**Comment by AlexandrouR** [comment]
@SweeXordious  @drinkcoffee  Hi all are working to resolve the issues related to some of the plugins the cli uses and are almost done, I will release the updated version of the CLI soon.

**Comment by drinkcoffee** [comment]
Thank you!

**Comment by hwangjr** [comment]
any process now? now the latest version is still 1.4.1

**Comment by kmkarim** [comment]
Any update on this one?

**Comment by tonghoang196** [comment]
wen release?

**Comment by ertra** [comment]
please update, thank you very much

**Comment by SweeXordious** [comment]
I don't have enough permissions to trigger a new release. One of the core team will need to do it.
@mohamedelshami

**Comment by dazito** [comment]
ser wen release?

**Comment by lukiholzi** [comment]
I am also waiting for a new release ^^

**Comment by conor10** [comment]
Let me find out what’s going on, apologies for the delay

**Comment by mohamedelshami** [comment]
I'm a bit behind here, but we've just done a release for Web3j-Cli which includes web3j 4.9.4

**Comment by mohamedelshami** [comment]
Closing this, please reopen if further investigation needed
