### ISSUE TITLE
Web3j on M1 is broken

### ISSUE THREAD

**Issue by thedarkknight197** [web3j/web3j-cli#87]
Hello when i run web3j new return me:

❯ web3j new
              _      _____ _ 
             | |    |____ (_)
__      _____| |__      / /_ 
\ \ /\ / / _ \ '_ \     \ \ |
 \ V  V /  __/ |_) |.___/ / |
  \_/\_/ \___|_.__/ \____/| |
                         _/ |
                        |__/ 
by Web3Labs
[ | ] Creating and building project ... Subsequent builds will be faster
Project generation Failed. Check log file for more information.

Log file:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':nodeSetup'.
> Could not resolve all files for configuration ':detachedConfiguration3'.
   > Could not find org.nodejs:node:12.18.1.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/nodejs/node/12.18.1/node-12.18.1.pom
       - https://repo.maven.apache.org/maven2/org/nodejs/node/12.18.1/node-12.18.1-darwin-arm64.tar.gz
       - https://jcenter.bintray.com/org/nodejs/node/12.18.1/node-12.18.1.pom
       - https://jcenter.bintray.com/org/nodejs/node/12.18.1/node-12.18.1-darwin-arm64.tar.gz
       - https://nodejs.org/dist/v12.18.1/node-v12.18.1-darwin-arm64.tar.gz
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

Macbook pro M1 Pro 16"  Version: MacOS 12.3.1 (21E258)

**Comment by gtebrean** [comment]
fixed in 1.5.0

**Comment by thedarkknight197** [comment]
Thank you so much
