### ISSUE TITLE
(No such file or directory)

### ISSUE THREAD

**Issue by jmichel-bc** [web3j/web3j-cli#89]
I am trying to generate a Solidity smart contract wrapper from an abi.

The abi is located in the same folder that I am running the command from, but the following fails:
`web3j generate solidity --abiFile ./token_ERC1155_IERC1155_sol_IERC1155.abi  --outputDir ./ --package package.name -c "Erc1155"`

The error I am getting is:
`token_ERC1155_IERC1155_sol_IERC1155.abi (No such file or directory)`

**Comment by mohamedelshami** [comment]
@jmichel-bc it's been a while on this issue, I'm going to close but please report again if this problem still persists.
